version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: banking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: banking_db
      MYSQL_USER: banking_user
      MYSQL_PASSWORD: banking_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
      - ./mock-data.sql:/docker-entrypoint-initdb.d/02-mock-data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: banking-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: banking-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      timeout: 10s
      retries: 3

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    container_name: banking-api
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - kafka
    environment:
      DATABASE_URL: mysql://banking_user:banking_pass@mysql:3306/banking_db
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LOG_LEVEL: INFO
      DEBUG: true
    volumes:
      - ./api-service:/app
      - ./db:/app/db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      timeout: 5s
      retries: 3

  consumer-service:
    build:
      context: ./consumer-service
      dockerfile: Dockerfile
    container_name: banking-consumer
    depends_on:
      - mysql
      - kafka
    environment:
      DATABASE_URL: mysql://banking_user:banking_pass@mysql:3306/banking_db
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      LOG_LEVEL: INFO
      DEBUG: true
    volumes:
      - ./consumer-service:/app
      - ./db:/app/db
volumes:
  mysql_data: